---
- name: Reproduce 'no-tabs' issues
  hosts: all

  roles:
    - no_tab_fail

  tasks:
    - name: Failing playbook example
      ansible.builtin.lineinfile:
        path: "/tmp/tab"
        line: "this\thas\ttabs"
